### ISSUE TITLE
Use ember-lazy-video?

### ISSUE THREAD

**Issue by elwayman02** [oskarrough/ember-youtube#20]
Would be great to use https://github.com/poteto/ember-lazy-video, adding your controls and such on top of the lazy-loading features of ember-lazy-video.

**Comment by friksa** [comment]
+1

**Comment by oskarrough** [comment]
Lazy-loading would definitely be nice.

I'm not sure how to compose the two components together as ember-lazy-video uses iframe embeds whereas ember-youtube relies on loading the videos through the YouTube Iframe API.

If lazy-loading should be enabled with a click that could be done directly in ember-youtube. But if we're interested in activating on the component being in the viewport etc. we should consider the great https://github.com/aFarkas/lazysizes plugin.

**Comment by oskarrough** [comment]
Not going to be able to pick this up anytime soon. If anyone wants to jump in, feel free!
