### ISSUE TITLE
Jumping to different timestamps in the video

### ISSUE THREAD

**Issue by andrefrmacedo** [oskarrough/ember-youtube#21]
Is it possible to jump to different timestamps in the video using an action (without clicking the progress bar)?

**Comment by oskarrough** [comment]
Definitely possible, but we'll need to write it. You're welcome to start it, otherwise hopefully I'll be able to do it next week.

Using the object syntax of `loadVideoById` https://developers.google.com/youtube/iframe_api_reference?hl=en#Queueing_Functions

**Comment by andrefrmacedo** [comment]
I'm fairly new to ember, but I'll definetly try it

**Comment by andrefrmacedo** [comment]
After a deeper look into your code I realized you already have the `seekTo` action implemented. We just need to call it targeting the component like this:

```hbs
{{action 'seekTo' seekTime target=myPlayer}}
```
with `seekTime` being the timestamp (in seconds) I want to jump to in the video.

However, since Ember 2.0, it is no longer possible to use `delegate=controller`. Instead we need to use `delegate=this`to make it available outside. So we have to use something like this: 
```hbs
{{ember-youtube ytid=youtubeId delegate=this delegate-as="myPlayer"}}
```

There's no need to write code, a simple update in the `README.md` file is enough to make the usage of this feature clearer.

**Comment by oskarrough** [comment]
Thank you for the reminder. I pushed a release 0.5.1.

https://github.com/oskarrough/ember-youtube/commit/9b74f6b53cedf8a0dd73d2033a15a8938b5eae4f
