### ISSUE TITLE
Update NPM version of ember-youtube

### ISSUE THREAD

**Issue by alobaidizt** [oskarrough/ember-youtube#22]
Hi there,

There have been few updates/merges in the past few months but the NPM version of ember-youtube doesn't reflect these desirable changes. It would be great if you can update npm with the latest version of ember-youtube. :smile: 

Ping me if I can be of help!

Ziyad

**Comment by oskarrough** [comment]
Here we go, 0.5.1 is out https://github.com/oskarrough/ember-youtube/releases

**Comment by alobaidizt** [comment]
Solid! Thank you!
