### ISSUE TITLE
It doesn't work when I switch routes

### ISSUE THREAD

**Issue by lancedikson** [oskarrough/ember-youtube#23]
Hi, I run into problem with YT API initialisation: when I got a component on the page it works fine for the first time rendering. But if I change route, and return back to the page with the component, and it doesn't work this time. This is because YT api frame doesn't load `www-widget.js` if it is loaded already. I'm going to send PR with fix that.

**Comment by lancedikson** [comment]
And I have Ember-CLI 2.2.0-beta.6, Ember 2.5.0-canary.

**Comment by oskarrough** [comment]
Thank you very much! Looks good.
