### ISSUE TITLE
Full screen?

### ISSUE THREAD

**Issue by lordkada** [oskarrough/ember-youtube#30]
Hi,

is it possible to enable the full screen on mobile?

**Comment by oskarrough** [comment]
This component shouldn't change anything to how the default YouTube iframe embeds work on mobile. Do you have anything specific in mind?

**Comment by lordkada** [comment]
I was just wondering why did you force the "fs" parameter to 0 (https://github.com/oskarrough/ember-youtube/blob/master/addon/components/ember-youtube.js#L45)...

**Comment by oskarrough** [comment]
Ah right, forgot all about that. Good catch —perhaps all the `playerVars` should be cleared out so we always run with YouTube defaults. And explain how you set your own.

**Comment by lordkada** [comment]
Yes, I agree... ;-)

**Comment by oskarrough** [comment]
https://github.com/oskarrough/ember-youtube/issues/10
