### ISSUE TITLE
Don't load YT script if it is already loaded

### ISSUE THREAD

**Issue by ArekOsiewicz** [oskarrough/ember-youtube#34]
onYouTubeIframeAPIReady is not called the second time. So player won't start.

**Comment by oskarrough** [comment]
You're right! That's no good.

I managed to reproduce it and believe I have fixed it on master now. Do you have a chance to verify before I publish a new release? It's on the `fix-multiple-videos` branch. If not, let me know and I'll push a new release as it seems to be working here with the fix.

https://github.com/oskarrough/ember-youtube/pull/35

**Comment by oskarrough** [comment]
Hi, this is now fixed https://github.com/oskarrough/ember-youtube/pull/35
