### ISSUE TITLE
Can't get ember-youtube to work on iOS safari or chrome

### ISSUE THREAD

**Issue by cosmikwolf** [oskarrough/ember-youtube#39]
Not sure what is going on here, but I'm hoping I could get a pointer.

On Chrome and Safari iOS when I go to Zetaohm.com, I don't see my youtube videos load at the bottom. In Safari on OS X, and Chrome on OS X it works fine. 

In Safari iOS I get the following error:

> Unable to post message to https://www.youtube.com. Recipient has origin http://zetaohm.herokuapp.com.

on both OS X and iOS, I get the following error: 
>Blocked a frame with origin "https://www.youtube.com" from accessing a frame with origin "http://zetaohm.com".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.
but on OS X it works fine. 

Any Ideas?

**Comment by oskarrough** [comment]
For the origin warning, please see https://developers.google.com/youtube/player_parameters#origin and https://github.com/oskarrough/ember-youtube#youtube-player-options. You should pass the `playerVars` object to the `ember-youtube` component and make sure it has an `origin` property configured with your domain.

If your site is using http and you try to embed a video from https, it will complain, but normally it does play anyway. I can't test on mobile atm.

**Comment by oskarrough** [comment]
Hi, closing this. It plays on my iPhone 5 but feel free to reopen if we should look again.
