### ISSUE TITLE
Progress bar won't update on click if video is paused

### ISSUE THREAD

**Issue by hybridmuse** [oskarrough/ember-youtube#42]
Clicking on the `<progress>` element won't update currentTime unless (until) video is playing. When video is paused, clicking on the HTML progress bar will only update the Youtube bar, resulting in a disconnection between the two. Pressing play will sync them back together again.

**Comment by oskarrough** [comment]
Thanks for reporting @hybridmuse, and thanks for fixing it @Darshan-Chauhan. Released in version 0.9.3.
