### ISSUE TITLE
ember-youtube rises some errors

### ISSUE THREAD

**Issue by mgonc** [oskarrough/ember-youtube#44]
The video works perfectly. However, rises some errors on console.
![image](https://user-images.githubusercontent.com/15728617/37364783-37e93b40-26da-11e8-9867-f8f54fcfbb8a.png)

**Comment by oskarrough** [comment]
Hey, thanks for reporting.

The `BLOCKED_BY_CLIENT` errors come from your adblocker.

But the first one with `Error while parsing the 'allow' attribute 'autoplay'` I'm not sure although it seems to come from YouTube and not this ember addon. See https://stackoverflow.com/questions/48247002/unrecognized-feature-autoplay-error-with-youtube-embedded-player.

Are you trying to set autoplay?

**Comment by mgonc** [comment]
Thanks for the reply, I'm not setting autoplay. However I tried set it and the error persist also doesn't autoplay the video.

**Comment by oskarrough** [comment]
Hm, can you provide me with an example? Here autoplay works for me https://ember-youtube.surge.sh/.

Note that autoplay isn't allowed on certain browsers, especially mobile.
