### ISSUE TITLE
Autoplay issues in iOS

### ISSUE THREAD

**Issue by adambarthelson** [oskarrough/ember-youtube#5]
The ember-youtube component auto-plays videos once it receives a new `ytid`, but on iOS this causes the player to break.

According to [Apple's documentation](https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/AudioandVideoTagBasics/AudioandVideoTagBasics.html), 

> "...embedded media cannot be played automatically in Safari on iOS - the user always initiates playback."

Instead of solely using `loadVideoById`, we should be using `cueVideoById` in cases like this.  As a workaround I used a simple viewport size check, but there should probably be a cleaner way to resolve this problem.  My workaround:

```
loadVideo: function() {
    var id = this.get('ytid'),
        load = (window.innerWidth ||document.body.clientWidth) > 600 ? 'loadVideoById':'cueVideoById';
    if (!id) return;
    this.get('player')[load](id);
}.observes('ytid'),

```

P.S. great project!  I was able to extend it pretty easily.  Will try to open a PR one of these days.

**Comment by oskarrough** [comment]
Thank you! It's really nice with some feedback.

How about changing from `loadVideoById` to `cueVideoById` followed by a `playVideo`? On iOS we'd skip the playVideo.

I'd like to keep the autoplay as it works on Android but we should make an option to disable it, for sure.

**Comment by adambarthelson** [comment]
Seems reasonable.

**Comment by oskarrough** [comment]
Note to self https://developers.google.com/youtube/iframe_api_reference#Mobile_considerations

**Comment by kitsunde** [comment]
If anyone else needs to fix this. Create `components/ember-youtube.js` with:

```js
import EmberYoutube from 'ember-youtube/components/ember-youtube';
import Ember from 'ember';

export default EmberYoutube.extend({
  iOS: Ember.computed(function(){
    return !!navigator.platform && /iPad|iPhone|iPod/.test(navigator.platform);
  }),

  // On iOS (iPad and mobile) youtube will put the video is a visually loading state perpetually if we try to
  // autoplay.
  loadVideo() {
    if(this.get('iOS')){
      this.playerVars.autoplay = false;
    }
    this._super(...arguments);
  }
});
```

**Comment by oskarrough** [comment]
@kitsunde thank for for sharing!

iOS 10 gives us some hope for the future: https://webkit.org/blog/6784/new-video-policies-for-ios/
