### ISSUE TITLE
sendAction deprication

### ISSUE THREAD

**Issue by Naomak** [oskarrough/ember-youtube#50]
Hi.

Can .sendAction() API calls be replaced by method calls, so there are no deprication warnings?

**Comment by T4JC** [comment]
> Hi.
> 
> Can .sendAction() API calls be replaced by method calls, so there are no deprication warnings?

For further info see:
https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_ember-component-send-action
"Deprecations Added in 3.4
Use closure actions instead of `sendAction`
until: 4.0.0
id: ember-component.send-action"

**Comment by Naomak** [comment]
Fixed in #59
