### ISSUE TITLE
Switching between multiple videos triggers a widget api error

### ISSUE THREAD

**Issue by T4JC** [oskarrough/ember-youtube#51]
I had experienced this within a code base I am currently working on and noticed it in the demo example here, to recreate in the demo:
1. Play a video on the main page.
2. Select the link at the bottom that states 'heres another video' 
3. The above triggers the following Message in the console:
`www-widgetapi.js:100 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://ember-youtube.surge.sh').`

Unsure as to what causes this I have seen other frameworks with the same problem and multiple solutions proposed for each but nothing definitive.

**Comment by T4JC** [comment]
@oskarrough 

Can confirm that fixes it on the demo site, awesome, thank you!

**Comment by oskarrough** [comment]
I added it to the readme, cheers!
