### ISSUE TITLE
modernize addon

### ISSUE THREAD

**Issue by 0xadada** [oskarrough/ember-youtube#54]
This addon could use some modernization luvin 💖:

* [x] convert `sendAction` to closure actions https://github.com/oskarrough/ember-youtube/issues/50
* [x] remove dependency on jQuery https://github.com/oskarrough/ember-youtube/pull/55
* [ ] convert to use latest Ember LTS (3.8)
* [ ] use prettier to standardize and enforce code style https://github.com/oskarrough/ember-youtube/pull/56
* [ ] convert addon to allow consumption via [angle bracket syntax](https://www.pzuraq.com/coming-soon-in-ember-octane-part-2-angle-brackets-and-named-arguments/)
* [ ] convert addon to use [native ES classes](https://www.pzuraq.com/coming-soon-in-ember-octane-part-1-native-classes/)

**Comment by oskarrough** [comment]
- [ ] upgrade ember concurrency https://github.com/oskarrough/ember-youtube/pull/58

**Comment by oskarrough** [comment]
Hey, I'm very sorry this never got merged. Are you still interested in it? I don't have any capacity to look at it I'm afraid.
