### ISSUE TITLE
Youtube message displayed instead of video

### ISSUE THREAD

**Issue by ferroariel** [oskarrough/ember-youtube#7]
Youtube videos are not being shown correctly. A youtube message vid is displayed instead. You can test it for yourself at http://mskber.alegoriaweb.com making a search for a music band.

**Comment by oskarrough** [comment]
Thank you. It seems this video will appear when using deprecated APIs: http://youtube-eng.blogspot.de/2014/03/committing-to-youtube-data-api-v3_4.html

Will have to investigate.

**Comment by oskarrough** [comment]
Not sure whether YouTube changed something but I'm not seeing this any longer. Feel free to reopen if it happens again.
